// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmXjWl_t8aVzpz7tt02ne5XFckrzGlajE',
    appId: '1:431191471451:web:3aa6e597649b20b909d67e',
    messagingSenderId: '431191471451',
    projectId: 'stage-209a8',
    authDomain: 'stage-209a8.firebaseapp.com',
    storageBucket: 'stage-209a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9LRPt4-64zglOOz-soIPtAo1SYrut_Zo',
    appId: '1:431191471451:android:a0d1ea02332e116c09d67e',
    messagingSenderId: '431191471451',
    projectId: 'stage-209a8',
    storageBucket: 'stage-209a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCugUkzG_vboKaSkDtl34YVJ_3HL1j-PnM',
    appId: '1:431191471451:ios:b432fdb1e11254f109d67e',
    messagingSenderId: '431191471451',
    projectId: 'stage-209a8',
    storageBucket: 'stage-209a8.appspot.com',
    iosClientId: '431191471451-kkqg9toocog5fh76ije5f4nhfrpoh7rg.apps.googleusercontent.com',
    iosBundleId: 'com.example.stage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCugUkzG_vboKaSkDtl34YVJ_3HL1j-PnM',
    appId: '1:431191471451:ios:f8170ead483af45b09d67e',
    messagingSenderId: '431191471451',
    projectId: 'stage-209a8',
    storageBucket: 'stage-209a8.appspot.com',
    iosClientId: '431191471451-2rnjv6rncn39pljgs0kkcg1bc98ruvue.apps.googleusercontent.com',
    iosBundleId: 'com.example.stage.RunnerTests',
  );
}
